name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check settings
      run: cd settings/ && cargo check --verbose
    - name: Check front
      run: cd front/ && cargo check --verbose
    - name: Check back
      run: cd back/ && cargo check --verbose

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build settings
      run: cd settings/ && cargo build --verbose
    - name: Build front
      run: cd front/ && cargo build --verbose
    - name: Build back
      run: cd back/ && cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test settings
      run: cd settings/ && cargo test --verbose
